### ISSUE TITLE
Installation Stuck

### ISSUE THREAD

**Issue by DRM-Scripts** [cline-pk/iptv-admin-panel-auto-installer-bash-script#1]
Installation hangs in Installing and Setting MySQL Server (longest time I've left is 1hr).

Server meets specs required.

![Screenshot 2022-06-06 150955](https://user-images.githubusercontent.com/85300094/172177596-59153531-c99f-431a-b5b7-47e1d2881a64.png)

**Comment by cline-pk** [comment]
Hi, please let me know which company server are you using and which OS
that script should be run on fresh Ubuntu 18.04 OS

**Comment by DRM-Scripts** [comment]
Tried on Hetzner Dedicated, OVH Dedicated, Hetzner VPS & Vultr VPS all way above your suggested minimum spec.

All using fresh U18.04 64bit

**Comment by cline-pk** [comment]
let we check

**Comment by cline-pk** [comment]
Check now please.

**Comment by DRM-Scripts** [comment]
Install now completes but the login details presented on finish screen don't login (Admin/qwerty).

**Comment by cline-pk** [comment]
that should be working, can you send your ip to check.

**Comment by cline-pk** [comment]
All Fixed.
