### ISSUE TITLE
Error in 22.04

### ISSUE THREAD

**Issue by DumberSoft** [cline-pk/iptv-admin-panel-auto-installer-bash-script#2]
Apparently it does not work with the linux version ubuntu 22.04 as I get the following error
![Sin título](https://github.com/cline-pk/iptv-admin-panel-auto-installer-bash-script/assets/16725154/f0e17849-4e57-42fc-a954-f096c3c6316c)

**Comment by Deltwin** [comment]
pip3 install requests

> Apparently it does not work with the linux version ubuntu 22.04 as I get the following error ![Sin título](https://private-user-images.githubusercontent.com/16725154/301337055-f0e17849-4e57-42fc-a954-f096c3c6316c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzc4MDIsIm5iZiI6MTcwNzM3NzUwMiwicGF0aCI6Ii8xNjcyNTE1NC8zMDEzMzcwNTUtZjBlMTc4NDktNGU1Ny00MmZjLWE5NTQtZjA5NmMzYzYzMTZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA3MzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MTI3MWQ1Nzg2YmVlMzU5MzU2N2JhOWQxZTcwNDdjNzM1MjQyZWY3ZDkzYWQxNmZiMjcxZDI0MjMyM2I3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tA55IsuprBLNYuTRfwzi4SzYab1ZVhXXtd_JN62oE_w)

**Comment by Kodiman1402** [comment]
Same problem

**Comment by cline-pk** [comment]
The issue is resolved, try proceed installation with u20 os.
